symfony/project/ads/src/Entity/Ad.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $author;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="boolean")
     */
    private $published;

    /**
    * @ORM\OneToOne(targetEntity="App\Entity\Image", cascade={"persist", "remove"})
    * @ORM\JoinColumn(nullable=false)
    */
    private $image;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(Image $image): self
    {
        $this->image = $image;

        return $this;
    }
}

symfony/project/ads/src/Controller/AdController.php
<?php

namespace App\Controller;

use Faker;
use App\Entity\Ad;
use App\Entity\Image;

use App\Entity\Application;

use App\Form\AdvertFormType;
use App\Repository\AdRepository;

use App\Repository\ImageRepository;
use App\Repository\ApplicationRepository;

use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class AdController extends AbstractController {
    /**
     * @Route("/", name="home_ad")
     */
    public function home() {
        $repo = $this->getDoctrine()->getRepository(Ad::class);
        $ad = $repo->findAllByDate();

        return $this->render('ad/home.html.twig', [
            'ads' => $ad
        ]);
    }

    /**
     * @Route("/accept", name="accept")
     */
    public function accept() {
        $repo = $this->getDoctrine()->getRepository(Ad::class);
        $ad = $repo->findAllByDate();

        return $this->render('ad/accept.html.twig', [
            'ads' => $ad
        ]);
    }

    /**
     * @Route("/del/{id}", name="del")
     */
    public function del($id) {
        $repo = $this->getDoctrine()->getManager();
        $ad = $repo->getRepository(Ad::class)->find($id);

        if (!$ad) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        }

        $repo->remove($ad);
        $repo->flush();

        return $this->redirectToRoute('home_ad');
    }

    /**
     * @Route("/publish/{id}", name="publish")
     */
    public function publish($id) {
        $repo = $this->getDoctrine()->getManager();
        $ad = $repo->getRepository(Ad::class)->find($id);

        if (!$ad) {
            throw $this->createNotFoundException(
                'No product found for id '.$id
            );
        }

        $ad->setPublished(true);
        $repo->flush();

        return $this->redirectToRoute('home_ad');
    }

    /**
     * @Route("/apply/{id}", name="apply")
     */
    public function apply(Request $req, $id) {
        $app = new Application;

        $form = $this->createFormBuilder($app)
                     ->add('author')
                     ->add('content')
                     ->getForm();
                     
        $form->handleRequest($req);

        $manager = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {
            $repo = $this->getDoctrine()->getRepository(Ad::class);
            $ad = $repo->findOneById($id);

            $app->setCreatedAt(new \DateTime());
            $app->setAdvert($ad);

            $manager->persist($app);
            $manager->flush();

            return $this->redirectToRoute('home', ['page' => $id]);
        }

        return $this->render('ad/candidate.html.twig', [
            'formAd' => $form->createView()
        ]);
    }

    /**
     * @Route("/add", name="add")
     * @Route("/edit/{id}", name="edit")
     */
    public function management(Ad $ad = null, Request $req) {
        if (!$ad) {
            $faker = Faker\Factory::create();

            $ad     = new Ad;
            $img    = new Image;

            $img->setUrl($faker->imageUrl('500', '500', 'people'));
            $img->setPath('une personne'); // path représente alt en réalité !
        }

        $form = $this->createForm(AdvertFormType::class, $ad);

        $form->handleRequest($req);

        $manager = $this->getDoctrine()->getManager();

        if ($form->isSubmitted() && $form->isValid()) {
            if (!$ad->getId()) {
                $ad->setCreatedAt(new \DateTime());
                $ad->setPublished(false);
                $ad->setImage($img);
            }

            $manager->persist($ad);
            $manager->flush();

            return $this->redirectToRoute('home_ad');
        }

        return $this->render('ad/management.html.twig', [
            'formAd' => $form->createView(),
            'isEdit' => $ad->getId() !== null
        ]);
    }

    /**
     * @Route("/{page}", name="home")
     */
    public function show($page) {
        $repo = $this->getDoctrine()->getRepository(Ad::class);
        $ad = $repo->findOneById($page);

        $repo = $this->getDoctrine()->getRepository(Application::class);
        $app = $repo->findByAdvertId($page);

        return $this->render('ad/show.html.twig', [
            'ad' => $ad,
            'applies' => $app
        ]);
    }
}

symfony/project/ads/templates/ad/accept.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block body %}

    {% set check = true %}

    <div class="row">
        {% for ad in ads %}
            {% if ad.published is same as(false) %}
                {% set check = false %}
                <div class="col-md-12">
                    <div class="card mb-4 my-4">
                        <img class="card-img-top card-img-top-show" src="{{ ad.image.url }}" alt="{{ ad.image.path }}">
                        <div class="card-body">
                            <h2 class="card-title">{{ ad.title }}</h2>
                            <hr>
                            <p class="card-text">{{ ad.content }}</p>
                        </div>
                        <div class="card-footer text-muted">
                            Posté le: {{ ad.createdAt | date('d/m/Y à H:i') }}
                            <small class="float-right">
                                <button 
                                    class="btn btn-danger" 
                                    onclick="window.location.href='{{ path('del', {'id': ad.id}) }}'"
                                >
                                    Refuser
                                </button>
                                <button 
                                    class="btn btn-success" 
                                    onclick="window.location.href='{{ path('publish', {'id': ad.id}) }}'"
                                >
                                    Publier
                                </button>
                            </small>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>

    {% if ads is empty or check is same as(true) %}
        <h1 style="text-align: center" class="center-to-middle">-Aucune annonce en attente-</h1>
    {% endif %}
    
{% endblock %}

symfony/project/ads/templates/ad/candidate.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block body %}
    <div class="mt-4">
        <h1>Postuler: </h1>

        {{ form_start(formAd) }}

        {{ form_row(formAd.content, {"attr": {"placeholder": "Description de l'annonce"}}) }}
        {{ form_row(formAd.author, {"attr": {"placeholder": "Votre identifiant"}}) }}

        <button type="submit" class="btn btn-success">Candidater</button>

        {{ form_end(formAd) }}
    </div>
{% endblock %}

symfony/project/ads/templates/ad/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block body %}

    {% if ads is empty %}
        <h1 style="text-align: center">-Aucune annonce-</h1>
    {% endif %}

    <div class="row">
        <div class="card-group"> 
        {% for ad in ads %}
            {% if ad.published is same as(true) %}
                <div class="col-md-3">
                    <div class="card mb-4">
                        <h4><strong>{{ ad.author }}</h4>
                        <img class="card-img-top" src="{{ ad.image.url }}" alt="{{ ad.image.path }}">
                        <div class="card-body">
                            <h5 class="card-title">
                                {{ ad.title | slice(0, 30) }}{% if ad.title | length > 30 %}<small>...</small>{% endif %}
                            </h5>
                            <a href="{{ path('home', {'page': ad.id}) }}" class="btn btn-primary">Voir plus &rarr;</a>
                        </div>
                        <div class="card-footer text-muted">
                            Posté le: {{ ad.createdAt | date('d/m/Y à H:i') }}</strong>
                        </div>
                    </div>
                </div> 
            {% endif %}
        {% endfor %}
        </div>
        <!-- <div class="col-2 category-div">
            <h3>Catégorie</h3>
        </div> -->
    </div>
{% endblock %}

symfony/project/ads/templates/ad/management.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block body %}
    <div class="mt-4">
        {% if isEdit %}
            <h1>Modifier l'annonce:</h1>
        {% else %}
            <h1>Créer une annonce:</h1>
        {% endif %}

        {{ form_start(formAd) }}

        {{ form_row(formAd.title, {"attr": {"placeholder": "Titre de l'annonce"}}) }}
        {{ form_row(formAd.content, {"attr": {"placeholder": "Description de l'annonce"}}) }}
        {{ form_row(formAd.author, {"attr": {"placeholder": "Votre identifiant"}}) }}

        {% if isEdit %}
            <button type="submit" class="btn btn-success">Modifer l'annonce</button>
        {% else %}
            <button type="submit" class="btn btn-success">Ajouter l'annonce</button>
        {% endif %}

        {{ form_end(formAd) }}
    </div>
{% endblock %}

symfony/project/ads/templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block body %}
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4 my-4">
            <img class="card-img-top card-img-top-show" src="{{ ad.image.url }}" alt="{{ ad.image.path }}">
            <div class="card-body">
                <h2 class="card-title">{{ ad.title }}</h2>
                <hr>
                <p class="card-text">{{ ad.content }}</p>
            </div>
            <div class="card-footer text-muted">
                Posté le: {{ ad.createdAt | date('d/m/Y à H:i') }}
                <small class="float-right">
                    <button 
                        class="btn btn-warning" 
                        onclick="window.location.href='{{ path('apply', {'id': ad.id}) }}'"
                    >
                        Candidater
                    </button>
                    <button 
                        class="btn btn-danger" 
                        onclick="window.location.href='{{ path('del', {'id': ad.id}) }}'"
                    >
                        Supprimer
                    </button>
                    <button 
                        class="btn btn-success" 
                        onclick="window.location.href='{{ path('edit', {'id': ad.id}) }}'"
                    >
                        éditer
                    </button>
                </small>
            </div>
        </div>
    </div>
</div>

{% if applies is not empty %}
    <div class="row">
        <div class="col">
            <h2>Liste des candidatures:</h2>
            <table class="table table-striped table-dark">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Auteur</th>
                    <th scope="col">Message</th>
                    <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
            {% for apply in applies %}
                    <tr>
                    <th scope="row">{{ loop.index }}</th>
                        <td>{{ apply.author }}</td>
                        <td>{{ apply.content }}</td>
                        <td>{{ apply.createdAt | date('d/m/Y à H:i') }}</td>
                    </tr>
            {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}

{% endblock %}